spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mysql://sql11.freemysqlhosting.net:3306/sql7724407
    driverClassName: com.mysql.jdbc.Driver
    username: sql7724407
    password: JFVk7Ue2iF
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
