package com.footballmanagergamesimulator.compartment;

/** Stable configuration keys for the attributes used by the V1 rating contract. */
public enum PlayerAttribute {
    FINISHING,
    LONG_SHOTS,
    OFF_THE_BALL,
    DRIBBLING,
    PASSING,
    VISION,
    TECHNIQUE,
    FIRST_TOUCH,
    ACCELERATION,
    PACE,
    COMPOSURE,
    DECISIONS,
    TEAMWORK,
    WORK_RATE,
    STAMINA,
    POSITIONING,
    ANTICIPATION,
    TACKLING,
    BALL_RECOVERY,
    MARKING,
    CONCENTRATION,
    STRENGTH,
    HEADING,
    BRAVERY,
    JUMPING_REACH,
    HANDLING,
    REFLEXES,
    ONE_ON_ONES,
    COMMAND_OF_AREA,
    KICKING,
    THROWING
}
