package com.footballmanagergamesimulator.integration;

import com.footballmanagergamesimulator.controller.CompetitionController;
import com.footballmanagergamesimulator.model.Competition;
import com.footballmanagergamesimulator.model.CompetitionTeamInfoDetail;
import com.footballmanagergamesimulator.model.CompetitionTeamInfoMatch;
import com.footballmanagergamesimulator.model.Scorer;
import com.footballmanagergamesimulator.model.Team;
import com.footballmanagergamesimulator.model.TeamCompetitionDetail;
import com.footballmanagergamesimulator.repository.CompetitionRepository;
import com.footballmanagergamesimulator.repository.CompetitionTeamInfoDetailRepository;
import com.footballmanagergamesimulator.repository.CompetitionTeamInfoMatchRepository;
import com.footballmanagergamesimulator.repository.HumanRepository;
import com.footballmanagergamesimulator.repository.ScorerRepository;
import com.footballmanagergamesimulator.repository.TeamCompetitionDetailRepository;
import com.footballmanagergamesimulator.repository.TeamRepository;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Order;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.stream.Collectors;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Golden-path integration test: boots the full Spring context (which triggers
 * the {@code @PostConstruct initializeRound()} bootstrap), then drives one
 * league through round 1 and asserts a set of structural invariants on the
 * resulting database state.
 *
 * <p>These invariants are what we'd lose if a refactor of {@code simulateRound},
 * the matchday persistence chain, or the standings update logic accidentally
 * skipped a step. The test is deliberately invariant-heavy (not "exact value"
 * assertions) so it stays stable across genuine random-engine variations.
 *
 * <p>One {@code @SpringBootTest} class = one Spring context per JVM = one
 * full game-world bootstrap. Currently ~7 leagues × 12 teams × 22 players
 * (~1850 humans). Boot is the dominant cost; the actual round simulation is
 * fast. Tests are ordered so the pre-bootstrap assertions run before the
 * round-1 simulation mutates state.
 */
@SpringBootTest
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
@DisplayName("Matchday invariants — round-1 league simulation")
class MatchdayInvariantsTest {

    @Autowired private CompetitionController competitionController;
    @Autowired private TeamRepository teamRepository;
    @Autowired private CompetitionRepository competitionRepository;
    @Autowired private HumanRepository humanRepository;
    @Autowired private CompetitionTeamInfoMatchRepository matchRepository;
    @Autowired private CompetitionTeamInfoDetailRepository detailRepository;
    @Autowired private TeamCompetitionDetailRepository teamCompDetailRepository;
    @Autowired private ScorerRepository scorerRepository;

    // ============================================================
    //  Pre-simulation invariants (verify bootstrap shape)
    // ============================================================

    @Test
    @Order(1)
    @DisplayName("Bootstrap: every team has at least 22 non-retired players")
    void bootstrap_everyTeamHasAtLeast22Players() {
        List<Team> teams = teamRepository.findAll();
        assertFalse(teams.isEmpty(), "bootstrap should have created teams");

        for (Team t : teams) {
            long active = humanRepository.findAllByTeamIdAndTypeId(t.getId(), 1L).stream()
                    .filter(h -> !h.isRetired())
                    .count();
            assertTrue(active >= 22,
                    "team " + t.getName() + " (id=" + t.getId() + ") should have >= 22 active players, got " + active);
        }
    }

    @Test
    @Order(2)
    @DisplayName("Bootstrap: at least one league has round-1 fixtures pre-generated")
    void bootstrap_leagueHasRoundOneFixtures() {
        Competition league = firstLeague();
        List<CompetitionTeamInfoMatch> r1 = matchRepository.findAllByCompetitionIdAndRoundAndSeasonNumber(
                league.getId(), 1L, "1");
        assertFalse(r1.isEmpty(),
                "league " + league.getName() + " round 1 should have fixtures pre-generated by initializeRound()");
    }

    // ============================================================
    //  Post-simulation invariants (single composite test — simulateRound
    //  mutates state, so we run it once and check everything from there)
    // ============================================================

    @Test
    @Order(10)
    @DisplayName("simulateRound: all invariants hold after round 1 of the first league")
    void simulateRound_allInvariantsHold() {
        Competition league = firstLeague();
        int fixtureCount = matchRepository.findAllByCompetitionIdAndRoundAndSeasonNumber(
                league.getId(), 1L, "1").size();
        assertTrue(fixtureCount > 0, "precondition: round-1 fixtures should exist");

        // -------- ACT --------
        competitionController.simulateRound(String.valueOf(league.getId()), "1");

        // -------- 1. Every fixture produced exactly one detail row, with a parseable score --------
        List<CompetitionTeamInfoDetail> details = detailRepository.findAllByCompetitionIdAndRoundIdAndSeasonNumber(
                league.getId(), 1L, 1L);
        assertEquals(fixtureCount, details.size(),
                "every round-1 fixture should produce exactly one detail row");
        long totalGoalsFromScores = 0;
        for (CompetitionTeamInfoDetail d : details) {
            assertNotNull(d.getScore(), "detail row id=" + d.getId() + " should have a score");
            int[] parsed = parseScore(d.getScore());
            assertTrue(parsed[0] >= 0 && parsed[1] >= 0,
                    "score should be non-negative ints, got " + d.getScore());
            totalGoalsFromScores += parsed[0] + parsed[1];
        }

        // -------- 2. Each team played exactly once in round 1 --------
        Map<Long, Integer> playCount = new HashMap<>();
        Set<Long> teamsInLeague = new HashSet<>();
        for (CompetitionTeamInfoDetail d : details) {
            playCount.merge(d.getTeam1Id(), 1, Integer::sum);
            playCount.merge(d.getTeam2Id(), 1, Integer::sum);
            teamsInLeague.add(d.getTeam1Id());
            teamsInLeague.add(d.getTeam2Id());
        }
        for (var entry : playCount.entrySet()) {
            assertEquals(1, entry.getValue(),
                    "team " + entry.getKey() + " should appear in exactly 1 fixture in round 1");
        }

        // -------- 3. Standings symmetric: goalsFor totals == goalsAgainst totals --------
        long totalGoalsFor = 0;
        long totalGoalsAgainst = 0;
        long totalWins = 0;
        long totalLoses = 0;
        long totalDraws = 0;
        long totalPoints = 0;
        long totalGames = 0;
        for (Long teamId : teamsInLeague) {
            TeamCompetitionDetail tcd = teamCompDetailRepository.findFirstByTeamIdAndCompetitionId(
                    teamId, league.getId());
            assertNotNull(tcd, "team " + teamId + " should have a TeamCompetitionDetail row after round 1");
            totalGoalsFor    += tcd.getGoalsFor();
            totalGoalsAgainst += tcd.getGoalsAgainst();
            totalWins   += tcd.getWins();
            totalLoses  += tcd.getLoses();
            totalDraws  += tcd.getDraws();
            totalPoints += tcd.getPoints();
            totalGames  += tcd.getGames();
        }
        assertEquals(totalGoalsFor, totalGoalsAgainst,
                "sum of goalsFor should equal sum of goalsAgainst across the league");
        assertEquals(totalWins, totalLoses,
                "every win on one side is a loss on the other — wins and losses must balance");
        assertEquals(0, totalDraws % 2,
                "draws total should be even (each draw counts on both team rows)");

        // -------- 4. Points math: every fixture awards 3 (decided) or 2 (draw) points --------
        long wonMatches = totalWins; // == totalLoses, == number of decided matches
        long drawnMatches = totalDraws / 2;
        assertEquals(fixtureCount, wonMatches + drawnMatches,
                "every fixture must end as either a win or a draw");
        assertEquals(3L * wonMatches + 2L * drawnMatches, totalPoints,
                "total points = 3 per decided match + 2 per draw");
        assertEquals(2L * fixtureCount, totalGames,
                "each fixture contributes 1 game to each team — total games = 2 × matches");

        // -------- 5. Scorer rows account for every goal in the league --------
        List<Scorer> scorers = scorerRepository.findAllByCompetitionIdAndSeasonNumber(league.getId(), 1);
        long scorerGoals = scorers.stream().mapToLong(Scorer::getGoals).sum();
        assertEquals(totalGoalsFromScores, scorerGoals,
                "sum of Scorer.goals should equal total goals scored across round-1 matches");
    }

    // ============================================================
    //  Multi-round invariants (extends round-1 by simulating rounds 2 & 3
    //  and checking cumulative aggregation). Runs AFTER the round-1 test
    //  via @Order so the DB state is "round 1 already complete".
    // ============================================================

    @Test
    @Order(20)
    @DisplayName("simulateRound: cumulative invariants hold after 3 rounds (aggregation works)")
    void multipleRounds_cumulativeInvariantsHold() {
        Competition league = firstLeague();

        // Round 1 was simulated by the previous test (@Order(10)). Continue
        // with rounds 2 and 3. League fixtures for all rounds are pre-generated
        // by initializeRound (getFixturesForRound at season start writes the
        // full round-robin schedule in one shot).
        competitionController.simulateRound(String.valueOf(league.getId()), "2");
        competitionController.simulateRound(String.valueOf(league.getId()), "3");

        // -------- Match count: each team appears in exactly 3 fixtures over rounds 1..3 --------
        List<CompetitionTeamInfoDetail> details = new java.util.ArrayList<>();
        for (long r = 1; r <= 3; r++) {
            details.addAll(detailRepository.findAllByCompetitionIdAndRoundIdAndSeasonNumber(
                    league.getId(), r, 1L));
        }
        Map<Long, Integer> playCount = new HashMap<>();
        Set<Long> teamsInLeague = new HashSet<>();
        long totalGoalsFromScores = 0;
        for (CompetitionTeamInfoDetail d : details) {
            playCount.merge(d.getTeam1Id(), 1, Integer::sum);
            playCount.merge(d.getTeam2Id(), 1, Integer::sum);
            teamsInLeague.add(d.getTeam1Id());
            teamsInLeague.add(d.getTeam2Id());
            int[] s = parseScore(d.getScore());
            totalGoalsFromScores += s[0] + s[1];
        }
        for (var entry : playCount.entrySet()) {
            assertEquals(3, entry.getValue(),
                    "team " + entry.getKey() + " should appear in exactly 3 fixtures over rounds 1..3");
        }
        int totalMatches = details.size();
        assertEquals(teamsInLeague.size() * 3 / 2, totalMatches,
                "3 rounds × (teams/2) matches per round — total match count should match");

        // -------- Per-team aggregation invariants --------
        long totalGoalsFor = 0;
        long totalGoalsAgainst = 0;
        long totalWins = 0;
        long totalLoses = 0;
        long totalDraws = 0;
        long totalPoints = 0;
        long totalGames = 0;
        for (Long teamId : teamsInLeague) {
            TeamCompetitionDetail tcd = teamCompDetailRepository.findFirstByTeamIdAndCompetitionId(
                    teamId, league.getId());
            assertNotNull(tcd, "team " + teamId + " should have a TeamCompetitionDetail row after 3 rounds");
            assertEquals(3, tcd.getGames(),
                    "team " + teamId + " should have games=3 after 3 rounds, got " + tcd.getGames());
            assertEquals(tcd.getWins() + tcd.getDraws() + tcd.getLoses(), tcd.getGames(),
                    "team " + teamId + ": wins + draws + loses must equal games");
            assertEquals(tcd.getGoalsFor() - tcd.getGoalsAgainst(), tcd.getGoalDifference(),
                    "team " + teamId + ": goalDifference must equal goalsFor − goalsAgainst");

            totalGoalsFor    += tcd.getGoalsFor();
            totalGoalsAgainst += tcd.getGoalsAgainst();
            totalWins   += tcd.getWins();
            totalLoses  += tcd.getLoses();
            totalDraws  += tcd.getDraws();
            totalPoints += tcd.getPoints();
            totalGames  += tcd.getGames();
        }
        assertEquals(totalGoalsFor, totalGoalsAgainst,
                "league-wide goalsFor must equal goalsAgainst after 3 rounds");
        assertEquals(totalWins, totalLoses,
                "league-wide wins must equal losses after 3 rounds");
        assertEquals(0, totalDraws % 2,
                "draws total must be even after 3 rounds");

        long wonMatches = totalWins;
        long drawnMatches = totalDraws / 2;
        assertEquals(totalMatches, wonMatches + drawnMatches,
                "every fixture across 3 rounds must end as either a win or a draw");
        assertEquals(3L * wonMatches + 2L * drawnMatches, totalPoints,
                "cumulative points = 3 per decided match + 2 per draw");
        assertEquals(2L * totalMatches, totalGames,
                "each fixture contributes 1 game to each team — total games = 2 × matches");

        // -------- Scorer accounting holds across rounds too --------
        List<Scorer> scorers = scorerRepository.findAllByCompetitionIdAndSeasonNumber(league.getId(), 1);
        long scorerGoals = scorers.stream().mapToLong(Scorer::getGoals).sum();
        assertEquals(totalGoalsFromScores, scorerGoals,
                "sum of Scorer.goals across season-1 should equal goals scored in rounds 1..3");

        // -------- No team has nonsensical stats --------
        for (Long teamId : teamsInLeague) {
            TeamCompetitionDetail tcd = teamCompDetailRepository.findFirstByTeamIdAndCompetitionId(
                    teamId, league.getId());
            assertTrue(tcd.getPoints() >= 0,
                    "points should never go negative (team " + teamId + " has " + tcd.getPoints() + ")");
            assertTrue(tcd.getPoints() <= 9,
                    "max 9 points after 3 rounds (3 wins × 3); team " + teamId + " has " + tcd.getPoints());
            assertTrue(tcd.getGoalsFor() >= 0 && tcd.getGoalsAgainst() >= 0,
                    "goals must be non-negative");
        }
    }

    // ============================================================
    //  Helpers
    // ============================================================

    /** Pick the first league competition (typeId == 1) from the seeded set. */
    private Competition firstLeague() {
        List<Competition> leagues = competitionRepository.findAll().stream()
                .filter(c -> c.getTypeId() == 1)
                .collect(Collectors.toList());
        assertFalse(leagues.isEmpty(), "bootstrap should have created at least one league");
        return leagues.get(0);
    }

    /** Parse "X-Y" → [X, Y]. Errors if the score is in any other shape. */
    private int[] parseScore(String score) {
        String[] parts = score.split("-");
        assertEquals(2, parts.length, "score should be 'X-Y' format, got " + score);
        return new int[] { Integer.parseInt(parts[0].trim()), Integer.parseInt(parts[1].trim()) };
    }
}
