CREATE TABLE game_room (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    singleton_key SMALLINT NOT NULL DEFAULT 1,
    name VARCHAR(80) NOT NULL DEFAULT 'Football Manager Room',
    host_user_id INTEGER NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    status VARCHAR(12) NOT NULL,
    continue_threshold_percent INTEGER NOT NULL,
    day_timeout_seconds INTEGER NOT NULL,
    majority_timeout_seconds INTEGER NOT NULL,
    max_players INTEGER NOT NULL,
    force_continue BOOLEAN NOT NULL DEFAULT FALSE,
    blocker_code VARCHAR(64),
    blocker_message VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    started_at TIMESTAMP WITH TIME ZONE,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_game_room_singleton UNIQUE (singleton_key),
    CONSTRAINT ck_game_room_singleton CHECK (singleton_key = 1),
    CONSTRAINT ck_room_status CHECK (status IN ('LOBBY', 'ACTIVE', 'CLOSED'))
);

CREATE TABLE game_room_member (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id BIGINT NOT NULL,
    user_id INTEGER NOT NULL,
    team_id BIGINT,
    ready BOOLEAN NOT NULL,
    membership_status VARCHAR(8) NOT NULL,
    fast_forward_enabled BOOLEAN NOT NULL,
    fast_forward_target_season INTEGER,
    fast_forward_target_day INTEGER,
    joined_at TIMESTAMP WITH TIME ZONE NOT NULL,
    last_seen_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_room_member_room FOREIGN KEY (room_id) REFERENCES game_room(id),
    CONSTRAINT uk_room_member_user UNIQUE (room_id, user_id),
    CONSTRAINT uk_room_member_team UNIQUE (room_id, team_id),
    CONSTRAINT ck_membership_status CHECK (membership_status IN ('ACTIVE', 'LEFT'))
);

CREATE TABLE room_continue_cycle (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id BIGINT NOT NULL,
    season INTEGER NOT NULL,
    game_day INTEGER NOT NULL,
    status VARCHAR(12) NOT NULL,
    opened_at TIMESTAMP WITH TIME ZONE NOT NULL,
    day_deadline TIMESTAMP WITH TIME ZONE NOT NULL,
    majority_reached_at TIMESTAMP WITH TIME ZONE,
    majority_deadline TIMESTAMP WITH TIME ZONE,
    advance_started_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    failure_code VARCHAR(255),
    advance_token VARCHAR(36),
    advance_lease_until TIMESTAMP WITH TIME ZONE,
    advance_execution_started_at TIMESTAMP WITH TIME ZONE,
    advance_mode VARCHAR(8),
    advance_force_continue BOOLEAN NOT NULL DEFAULT FALSE,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_cycle_room FOREIGN KEY (room_id) REFERENCES game_room(id),
    CONSTRAINT uk_cycle_date UNIQUE (room_id, season, game_day)
);

CREATE TABLE room_continue_vote (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cycle_id BIGINT NOT NULL,
    user_id INTEGER NOT NULL,
    source VARCHAR(16) NOT NULL,
    voted_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_vote_cycle FOREIGN KEY (cycle_id) REFERENCES room_continue_cycle(id),
    CONSTRAINT uk_vote_user UNIQUE (cycle_id, user_id),
    CONSTRAINT ck_vote_source CHECK (source IN ('MANUAL', 'FAST_FORWARD'))
);
