ALTER TABLE human ADD COLUMN IF NOT EXISTS wealth BIGINT DEFAULT 0 NOT NULL;
ALTER TABLE human ADD COLUMN IF NOT EXISTS career_earnings BIGINT DEFAULT 0 NOT NULL;

CREATE TABLE IF NOT EXISTS asset (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_human_id BIGINT NOT NULL,
    type VARCHAR(10),
    name VARCHAR(255),
    asset_value BIGINT DEFAULT 0 NOT NULL,
    club_team_id BIGINT
);

DELETE FROM person_profile
WHERE user_id IS NULL
  AND human_id IN (SELECT id FROM human WHERE type_id NOT IN (1, 4));

CREATE TABLE IF NOT EXISTS personal_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL,
    owner_user_id INTEGER,
    owner_human_id BIGINT,
    cash_balance BIGINT DEFAULT 0 NOT NULL,
    lifetime_career_earnings BIGINT DEFAULT 0 NOT NULL,
    realized_investment_gain BIGINT DEFAULT 0 NOT NULL,
    version BIGINT DEFAULT 0 NOT NULL,
    CONSTRAINT uk_personal_account_profile UNIQUE (profile_id),
    CONSTRAINT uk_personal_account_user UNIQUE (owner_user_id),
    CONSTRAINT uk_personal_account_human UNIQUE (owner_human_id),
    CONSTRAINT ck_personal_account_cash_nonnegative CHECK (cash_balance >= 0),
    CONSTRAINT ck_personal_account_earnings_nonnegative CHECK (lifetime_career_earnings >= 0)
);

CREATE TABLE IF NOT EXISTS personal_ledger_entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    profile_id BIGINT NOT NULL,
    season_number INTEGER DEFAULT 0 NOT NULL,
    game_day INTEGER DEFAULT 0 NOT NULL,
    entry_type VARCHAR(40) NOT NULL,
    signed_amount BIGINT NOT NULL,
    career_earnings_delta BIGINT DEFAULT 0 NOT NULL,
    balance_after BIGINT NOT NULL,
    correlation_id VARCHAR(120) NOT NULL,
    idempotency_key VARCHAR(160) NOT NULL,
    counterpart_team_id BIGINT,
    counterpart_asset_id BIGINT,
    description VARCHAR(300) NOT NULL,
    created_at BIGINT NOT NULL,
    CONSTRAINT uk_personal_ledger_idempotency UNIQUE (account_id, idempotency_key),
    CONSTRAINT ck_personal_ledger_balance_nonnegative CHECK (balance_after >= 0)
);

CREATE INDEX IF NOT EXISTS idx_personal_ledger_account_id
    ON personal_ledger_entry(account_id, id);
CREATE INDEX IF NOT EXISTS idx_personal_ledger_correlation
    ON personal_ledger_entry(correlation_id);

CREATE TABLE IF NOT EXISTS asset_catalog_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(60) NOT NULL,
    asset_type VARCHAR(20) NOT NULL,
    apartment_rooms INTEGER,
    name VARCHAR(120) NOT NULL,
    icon_key VARCHAR(80) NOT NULL,
    purchase_price BIGINT NOT NULL,
    resale_haircut_bps INTEGER DEFAULT 1000 NOT NULL,
    active BOOLEAN DEFAULT TRUE NOT NULL,
    version BIGINT DEFAULT 0 NOT NULL,
    CONSTRAINT uk_asset_catalog_code UNIQUE (code),
    CONSTRAINT ck_asset_catalog_price_positive CHECK (purchase_price > 0),
    CONSTRAINT ck_asset_catalog_haircut CHECK (resale_haircut_bps BETWEEN 0 AND 10000),
    CONSTRAINT ck_asset_catalog_apartment_rooms CHECK (
        (asset_type = 'APARTMENT' AND apartment_rooms BETWEEN 1 AND 4)
        OR (asset_type <> 'APARTMENT' AND apartment_rooms IS NULL))
);

CREATE TABLE IF NOT EXISTS owned_asset (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    profile_id BIGINT NOT NULL,
    catalog_item_id BIGINT NOT NULL,
    purchase_price BIGINT NOT NULL,
    current_value BIGINT NOT NULL,
    purchase_season INTEGER DEFAULT 0 NOT NULL,
    purchase_day INTEGER DEFAULT 0 NOT NULL,
    status VARCHAR(20) NOT NULL,
    purchase_idempotency_key VARCHAR(160) NOT NULL,
    sale_idempotency_key VARCHAR(160),
    sale_price BIGINT,
    sale_season INTEGER,
    sale_day INTEGER,
    version BIGINT DEFAULT 0 NOT NULL,
    CONSTRAINT uk_owned_asset_purchase_retry UNIQUE (account_id, purchase_idempotency_key),
    CONSTRAINT uk_owned_asset_sale_retry UNIQUE (account_id, sale_idempotency_key),
    CONSTRAINT ck_owned_asset_values_nonnegative CHECK (
        purchase_price >= 0 AND current_value >= 0 AND (sale_price IS NULL OR sale_price >= 0))
);

CREATE INDEX IF NOT EXISTS idx_owned_asset_account_status ON owned_asset(account_id, status);

ALTER TABLE personal_account ADD CONSTRAINT IF NOT EXISTS fk_personal_account_profile
    FOREIGN KEY (profile_id) REFERENCES person_profile(id);
ALTER TABLE personal_ledger_entry ADD CONSTRAINT IF NOT EXISTS fk_personal_ledger_account
    FOREIGN KEY (account_id) REFERENCES personal_account(id);
ALTER TABLE owned_asset ADD CONSTRAINT IF NOT EXISTS fk_owned_asset_account
    FOREIGN KEY (account_id) REFERENCES personal_account(id);
ALTER TABLE owned_asset ADD CONSTRAINT IF NOT EXISTS fk_owned_asset_catalog
    FOREIGN KEY (catalog_item_id) REFERENCES asset_catalog_item(id);

INSERT INTO asset_catalog_item
    (code, asset_type, apartment_rooms, name, icon_key, purchase_price, resale_haircut_bps, active, version)
SELECT 'APARTMENT_1_ROOM', 'APARTMENT', 1, 'One-room Apartment', 'apartment-1', 150000, 1000, TRUE, 0
WHERE NOT EXISTS (SELECT 1 FROM asset_catalog_item WHERE code = 'APARTMENT_1_ROOM');
INSERT INTO asset_catalog_item
    (code, asset_type, apartment_rooms, name, icon_key, purchase_price, resale_haircut_bps, active, version)
SELECT 'APARTMENT_2_ROOMS', 'APARTMENT', 2, 'Two-room Apartment', 'apartment-2', 260000, 1000, TRUE, 0
WHERE NOT EXISTS (SELECT 1 FROM asset_catalog_item WHERE code = 'APARTMENT_2_ROOMS');
INSERT INTO asset_catalog_item
    (code, asset_type, apartment_rooms, name, icon_key, purchase_price, resale_haircut_bps, active, version)
SELECT 'APARTMENT_3_ROOMS', 'APARTMENT', 3, 'Three-room Apartment', 'apartment-3', 420000, 1000, TRUE, 0
WHERE NOT EXISTS (SELECT 1 FROM asset_catalog_item WHERE code = 'APARTMENT_3_ROOMS');
INSERT INTO asset_catalog_item
    (code, asset_type, apartment_rooms, name, icon_key, purchase_price, resale_haircut_bps, active, version)
SELECT 'APARTMENT_4_ROOMS', 'APARTMENT', 4, 'Four-room Apartment', 'apartment-4', 650000, 1000, TRUE, 0
WHERE NOT EXISTS (SELECT 1 FROM asset_catalog_item WHERE code = 'APARTMENT_4_ROOMS');
INSERT INTO asset_catalog_item
    (code, asset_type, apartment_rooms, name, icon_key, purchase_price, resale_haircut_bps, active, version)
SELECT 'VILLA_CLASSIC', 'VILLA', NULL, 'Classic Villa', 'villa-classic', 2500000, 1200, TRUE, 0
WHERE NOT EXISTS (SELECT 1 FROM asset_catalog_item WHERE code = 'VILLA_CLASSIC');
INSERT INTO asset_catalog_item
    (code, asset_type, apartment_rooms, name, icon_key, purchase_price, resale_haircut_bps, active, version)
SELECT 'HOTEL_BOUTIQUE', 'HOTEL', NULL, 'Boutique Hotel', 'hotel-boutique', 15000000, 1500, TRUE, 0
WHERE NOT EXISTS (SELECT 1 FROM asset_catalog_item WHERE code = 'HOTEL_BOUTIQUE');
INSERT INTO asset_catalog_item
    (code, asset_type, apartment_rooms, name, icon_key, purchase_price, resale_haircut_bps, active, version)
SELECT 'CAR_SPORT', 'CAR', NULL, 'Sports Car', 'car-sport', 300000, 2000, TRUE, 0
WHERE NOT EXISTS (SELECT 1 FROM asset_catalog_item WHERE code = 'CAR_SPORT');
INSERT INTO asset_catalog_item
    (code, asset_type, apartment_rooms, name, icon_key, purchase_price, resale_haircut_bps, active, version)
SELECT 'CAR_LUXURY', 'CAR', NULL, 'Luxury Car', 'car-luxury', 750000, 2000, TRUE, 0
WHERE NOT EXISTS (SELECT 1 FROM asset_catalog_item WHERE code = 'CAR_LUXURY');

INSERT INTO personal_account
    (profile_id, owner_user_id, owner_human_id, cash_balance,
     lifetime_career_earnings, realized_investment_gain, version)
SELECT p.id, p.user_id, p.human_id,
       CASE WHEN p.career_type = 'CHAIRMAN' AND p.human_id IS NULL THEN 10000000
            ELSE GREATEST(COALESCE(h.wealth, 0), 0) END,
       GREATEST(COALESCE(h.career_earnings, 0), 0), 0, 0
FROM person_profile p
LEFT JOIN human h ON h.id = p.human_id
WHERE p.career_type IN ('PLAYER', 'MANAGER', 'CHAIRMAN')
  AND NOT EXISTS (SELECT 1 FROM personal_account a WHERE a.profile_id = p.id);

INSERT INTO personal_ledger_entry
    (account_id, profile_id, season_number, game_day, entry_type, signed_amount,
     career_earnings_delta, balance_after, correlation_id, idempotency_key,
     description, created_at)
SELECT a.id, a.profile_id, 0, 0, 'MIGRATION_OPENING', a.cash_balance,
       a.lifetime_career_earnings, a.cash_balance,
       CONCAT('PROFILE-MIGRATION:', a.profile_id), CONCAT('PROFILE-MIGRATION:', a.profile_id),
       'Migrated opening balance', 0
FROM personal_account a
WHERE (a.cash_balance <> 0 OR a.lifetime_career_earnings <> 0)
  AND NOT EXISTS (SELECT 1 FROM personal_ledger_entry l WHERE l.account_id = a.id);

INSERT INTO owned_asset
    (account_id, profile_id, catalog_item_id, purchase_price, current_value,
     purchase_season, purchase_day, status, purchase_idempotency_key, version)
SELECT pa.id, pa.profile_id, catalog.id,
       GREATEST(legacy.asset_value, 0), GREATEST(legacy.asset_value, 0),
       0, 0, 'OWNED', CONCAT('LEGACY-ASSET:', legacy.id), 0
FROM asset legacy
JOIN personal_account pa ON pa.owner_human_id = legacy.owner_human_id
JOIN asset_catalog_item catalog
  ON catalog.code = CASE WHEN legacy.type = 'CAR' THEN 'CAR_SPORT' ELSE 'VILLA_CLASSIC' END
WHERE legacy.type IN ('HOUSE', 'CAR')
  AND NOT EXISTS (
      SELECT 1 FROM owned_asset owned
      WHERE owned.account_id = pa.id
        AND owned.purchase_idempotency_key = CONCAT('LEGACY-ASSET:', legacy.id));
