CREATE TABLE IF NOT EXISTS market_instrument (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(80) NOT NULL,
    instrument_type VARCHAR(20) NOT NULL,
    team_id BIGINT,
    name VARCHAR(160) NOT NULL,
    total_supply BIGINT NOT NULL,
    available_supply BIGINT NOT NULL,
    current_price BIGINT NOT NULL,
    price_seed BIGINT NOT NULL,
    price_algorithm_version VARCHAR(32) DEFAULT 'market-v1' NOT NULL,
    daily_limit_bps INTEGER NOT NULL,
    weekly_limit_bps INTEGER NOT NULL,
    active BOOLEAN DEFAULT TRUE NOT NULL,
    version BIGINT DEFAULT 0 NOT NULL,
    CONSTRAINT uk_market_instrument_code UNIQUE (code),
    CONSTRAINT uk_market_instrument_team UNIQUE (team_id),
    CONSTRAINT ck_market_instrument_type CHECK (instrument_type IN ('COMPANY', 'CLUB')),
    CONSTRAINT ck_market_instrument_supply CHECK (
        total_supply > 0 AND available_supply >= 0 AND available_supply <= total_supply),
    CONSTRAINT ck_market_instrument_price CHECK (current_price > 0),
    CONSTRAINT ck_market_instrument_limits CHECK (
        daily_limit_bps BETWEEN 0 AND 10000
        AND weekly_limit_bps BETWEEN daily_limit_bps AND 10000),
    CONSTRAINT ck_market_instrument_team_type CHECK (
        (instrument_type = 'CLUB' AND team_id IS NOT NULL)
        OR (instrument_type = 'COMPANY' AND team_id IS NULL))
);

CREATE TABLE IF NOT EXISTS market_price_snapshot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instrument_id BIGINT NOT NULL,
    season_number INTEGER NOT NULL,
    game_day INTEGER NOT NULL,
    previous_close BIGINT NOT NULL,
    close_price BIGINT NOT NULL,
    weekly_anchor_price BIGINT NOT NULL,
    daily_change_bps INTEGER NOT NULL,
    algorithm_version VARCHAR(32) DEFAULT 'market-v1' NOT NULL,
    deterministic_hash BIGINT DEFAULT 0 NOT NULL,
    CONSTRAINT uk_market_price_day UNIQUE (instrument_id, season_number, game_day),
    CONSTRAINT ck_market_price_date CHECK (season_number >= 1 AND game_day BETWEEN 1 AND 366),
    CONSTRAINT ck_market_price_positive CHECK (
        previous_close > 0 AND close_price > 0 AND weekly_anchor_price > 0),
    CONSTRAINT fk_market_price_instrument FOREIGN KEY (instrument_id) REFERENCES market_instrument(id)
);
CREATE INDEX IF NOT EXISTS idx_market_price_history
    ON market_price_snapshot(instrument_id, season_number, game_day);

CREATE TABLE IF NOT EXISTS portfolio_position (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    profile_id BIGINT NOT NULL,
    instrument_id BIGINT NOT NULL,
    quantity BIGINT NOT NULL,
    total_cost_basis BIGINT NOT NULL,
    version BIGINT DEFAULT 0 NOT NULL,
    CONSTRAINT uk_portfolio_account_instrument UNIQUE (account_id, instrument_id),
    CONSTRAINT ck_portfolio_nonnegative CHECK (quantity >= 0 AND total_cost_basis >= 0),
    CONSTRAINT ck_portfolio_zero_basis CHECK (quantity <> 0 OR total_cost_basis = 0),
    CONSTRAINT fk_portfolio_account FOREIGN KEY (account_id) REFERENCES personal_account(id),
    CONSTRAINT fk_portfolio_instrument FOREIGN KEY (instrument_id) REFERENCES market_instrument(id)
);

CREATE TABLE IF NOT EXISTS market_trade (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    profile_id BIGINT NOT NULL,
    instrument_id BIGINT NOT NULL,
    side VARCHAR(10) NOT NULL,
    quantity BIGINT NOT NULL,
    unit_price BIGINT NOT NULL,
    gross_amount BIGINT NOT NULL,
    cost_basis_amount BIGINT NOT NULL,
    realized_gain BIGINT NOT NULL,
    season_number INTEGER NOT NULL,
    game_day INTEGER NOT NULL,
    idempotency_key VARCHAR(160) NOT NULL,
    correlation_id VARCHAR(160) NOT NULL,
    cash_balance_after BIGINT NOT NULL,
    quantity_after BIGINT NOT NULL,
    cost_basis_after BIGINT NOT NULL,
    CONSTRAINT uk_market_trade_retry UNIQUE (account_id, idempotency_key),
    CONSTRAINT ck_market_trade_side CHECK (side IN ('BUY', 'SELL')),
    CONSTRAINT ck_market_trade_values CHECK (
        quantity > 0 AND unit_price > 0 AND gross_amount > 0
        AND cost_basis_amount >= 0 AND cash_balance_after >= 0
        AND quantity_after >= 0 AND cost_basis_after >= 0),
    CONSTRAINT fk_market_trade_account FOREIGN KEY (account_id) REFERENCES personal_account(id),
    CONSTRAINT fk_market_trade_instrument FOREIGN KEY (instrument_id) REFERENCES market_instrument(id)
);
CREATE INDEX IF NOT EXISTS idx_market_trade_account ON market_trade(account_id, id);

INSERT INTO market_instrument
    (code, instrument_type, team_id, name, total_supply, available_supply,
     current_price, price_seed, daily_limit_bps, weekly_limit_bps, active, version)
SELECT 'FMX', 'COMPANY', NULL, 'Football Markets Exchange', 1000000, 1000000,
       1250, 772360782, 700, 5000, TRUE, 0
WHERE NOT EXISTS (SELECT 1 FROM market_instrument WHERE code = 'FMX');

INSERT INTO market_instrument
    (code, instrument_type, team_id, name, total_supply, available_supply,
     current_price, price_seed, daily_limit_bps, weekly_limit_bps, active, version)
SELECT 'SPORTTECH', 'COMPANY', NULL, 'Sport Technology Group', 1000000, 1000000,
       850, 1297702381, 700, 5000, TRUE, 0
WHERE NOT EXISTS (SELECT 1 FROM market_instrument WHERE code = 'SPORTTECH');

INSERT INTO market_instrument
    (code, instrument_type, team_id, name, total_supply, available_supply,
     current_price, price_seed, daily_limit_bps, weekly_limit_bps, active, version)
SELECT 'MEDIA11', 'COMPANY', NULL, 'Eleven Sports Media', 1000000, 1000000,
       640, 214013921, 700, 5000, TRUE, 0
WHERE NOT EXISTS (SELECT 1 FROM market_instrument WHERE code = 'MEDIA11');
