-- ADI Analytics Option B, Phase 0 — canonical identity, provenance & parity gate.
-- H2-only, additive. One row per canonical fixture, keyed by the existing
-- "CTIM:<matchRowId>" fixture key. The UNIQUE constraint on fixture_key is what
-- makes the provenance stamp idempotent (retry / concurrent commit -> one row).
-- No score, event or football metric is stored here.
--
-- OVERLAP NOTE: REGENT Phase 3 also branches from base 90cf15b and will
-- independently add an h2/V4 migration + bump the save version; ATLAS reconciles
-- the file numbering and save-version ordering at integration.
CREATE TABLE IF NOT EXISTS match_provenance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fixture_key VARCHAR(120) NOT NULL,
    source_kind VARCHAR(32) NOT NULL,
    engine_version VARCHAR(64),
    schema_version INTEGER NOT NULL,
    reconciliation_status VARCHAR(32) NOT NULL,
    reconciliation_detail VARCHAR(1024),
    competition_id BIGINT NOT NULL,
    season_number INTEGER NOT NULL,
    round_number INTEGER NOT NULL,
    home_team_id BIGINT NOT NULL,
    away_team_id BIGINT NOT NULL,
    CONSTRAINT uk_match_provenance_fixture_key UNIQUE (fixture_key),
    CONSTRAINT ck_match_provenance_source_kind CHECK (
        source_kind IN ('INSTANT', 'AI', 'INTERACTIVE_LIVE', 'FAST_FORWARD', 'LEGACY_UNVERSIONED')),
    CONSTRAINT ck_match_provenance_status CHECK (
        reconciliation_status IN ('MATCH', 'MISMATCH', 'NOT_APPLICABLE', 'PENDING')),
    CONSTRAINT ck_match_provenance_schema_version CHECK (schema_version >= 1)
);

CREATE INDEX IF NOT EXISTS idx_match_provenance_comp_season_round
    ON match_provenance(competition_id, season_number, round_number);
