-- FORGE Squad Planner — persistent depth chart across three season horizons.
-- H2-only, mirroring the REGENT V2/V3 precedent (ddl-auto creates the table on
-- other dialects; save/load for this table is H2-only via SAVE_VERSION_9).
CREATE TABLE IF NOT EXISTS squad_plan_slot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    team_id BIGINT NOT NULL,
    season_offset INTEGER NOT NULL,
    base_season INTEGER NOT NULL,
    position VARCHAR(10) NOT NULL,
    depth_order INTEGER DEFAULT 1 NOT NULL,
    player_id BIGINT,
    role VARCHAR(80),
    role_familiarity INTEGER,
    priority INTEGER DEFAULT 0 NOT NULL,
    planned_sale BOOLEAN DEFAULT FALSE NOT NULL,
    planned_loan BOOLEAN DEFAULT FALSE NOT NULL,
    youth_promotion BOOLEAN DEFAULT FALSE NOT NULL,
    recruitment_need BOOLEAN DEFAULT FALSE NOT NULL,
    locked BOOLEAN DEFAULT FALSE NOT NULL,
    notes VARCHAR(500),
    version BIGINT DEFAULT 0 NOT NULL,
    CONSTRAINT ck_squad_plan_slot_offset CHECK (season_offset BETWEEN 0 AND 2),
    CONSTRAINT ck_squad_plan_slot_depth CHECK (depth_order >= 1),
    CONSTRAINT ck_squad_plan_slot_priority CHECK (priority BETWEEN 0 AND 2)
);

CREATE INDEX IF NOT EXISTS idx_squad_plan_slot_team_offset
    ON squad_plan_slot (team_id, season_offset);
CREATE INDEX IF NOT EXISTS idx_squad_plan_slot_user_team
    ON squad_plan_slot (user_id, team_id);
