CREATE TABLE IF NOT EXISTS club_cap_table_state (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instrument_id BIGINT NOT NULL,
    team_id BIGINT NOT NULL,
    migration_version INTEGER DEFAULT 0 NOT NULL,
    controlling_account_id BIGINT,
    control_threshold_bps INTEGER DEFAULT 5001 NOT NULL,
    version BIGINT DEFAULT 0 NOT NULL,
    CONSTRAINT uk_club_cap_table_instrument UNIQUE (instrument_id),
    CONSTRAINT uk_club_cap_table_team UNIQUE (team_id),
    CONSTRAINT ck_club_cap_table_threshold CHECK (control_threshold_bps BETWEEN 5001 AND 10000),
    CONSTRAINT fk_club_cap_table_instrument FOREIGN KEY (instrument_id) REFERENCES market_instrument(id),
    CONSTRAINT fk_club_cap_table_controller FOREIGN KEY (controlling_account_id) REFERENCES personal_account(id)
);

CREATE TABLE IF NOT EXISTS club_financial_obligation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id BIGINT NOT NULL,
    category VARCHAR(80) NOT NULL,
    amount_remaining BIGINT NOT NULL,
    due_season INTEGER NOT NULL,
    due_day INTEGER NOT NULL,
    restricts_withdrawal BOOLEAN DEFAULT FALSE NOT NULL,
    settled BOOLEAN DEFAULT FALSE NOT NULL,
    CONSTRAINT ck_club_obligation_amount CHECK (amount_remaining >= 0)
);
CREATE INDEX IF NOT EXISTS idx_club_obligation_team_due
    ON club_financial_obligation(team_id, settled, due_season, due_day);

CREATE TABLE IF NOT EXISTS takeover_quote (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quote_key VARCHAR(36) NOT NULL,
    buyer_account_id BIGINT NOT NULL,
    buyer_profile_id BIGINT NOT NULL,
    instrument_id BIGINT NOT NULL,
    team_id BIGINT NOT NULL,
    valuation_formula_version VARCHAR(40) NOT NULL,
    valuation_state_version VARCHAR(64) NOT NULL,
    instrument_version BIGINT NOT NULL,
    issued_shares BIGINT NOT NULL,
    shares_to_acquire BIGINT NOT NULL,
    unit_price BIGINT NOT NULL,
    premium_bps INTEGER NOT NULL,
    total_consideration BIGINT NOT NULL,
    quoted_season INTEGER NOT NULL,
    quoted_day INTEGER NOT NULL,
    expires_absolute_day BIGINT NOT NULL,
    idempotency_key VARCHAR(140) NOT NULL,
    status VARCHAR(16) NOT NULL,
    version BIGINT DEFAULT 0 NOT NULL,
    CONSTRAINT uk_takeover_quote_public UNIQUE (quote_key),
    CONSTRAINT uk_takeover_quote_retry UNIQUE (buyer_account_id, idempotency_key),
    CONSTRAINT ck_takeover_quote_values CHECK (
        issued_shares > 0 AND shares_to_acquire > 0 AND shares_to_acquire <= issued_shares
        AND unit_price > 0 AND premium_bps >= 0 AND total_consideration > 0
        AND status IN ('OPEN', 'EXECUTED')),
    CONSTRAINT fk_takeover_quote_account FOREIGN KEY (buyer_account_id) REFERENCES personal_account(id),
    CONSTRAINT fk_takeover_quote_instrument FOREIGN KEY (instrument_id) REFERENCES market_instrument(id)
);

CREATE TABLE IF NOT EXISTS takeover_execution (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    execution_key VARCHAR(36) NOT NULL,
    quote_id BIGINT NOT NULL,
    buyer_account_id BIGINT NOT NULL,
    buyer_profile_id BIGINT NOT NULL,
    instrument_id BIGINT NOT NULL,
    team_id BIGINT NOT NULL,
    shares_acquired BIGINT NOT NULL,
    unit_price BIGINT NOT NULL,
    total_consideration BIGINT NOT NULL,
    season_number INTEGER NOT NULL,
    game_day INTEGER NOT NULL,
    idempotency_key VARCHAR(140) NOT NULL,
    correlation_id VARCHAR(120) NOT NULL,
    cash_balance_after BIGINT NOT NULL,
    quantity_after BIGINT NOT NULL,
    CONSTRAINT uk_takeover_execution_public UNIQUE (execution_key),
    CONSTRAINT uk_takeover_execution_quote UNIQUE (quote_id),
    CONSTRAINT uk_takeover_execution_retry UNIQUE (buyer_account_id, idempotency_key),
    CONSTRAINT ck_takeover_execution_values CHECK (
        shares_acquired > 0 AND unit_price > 0 AND total_consideration > 0
        AND cash_balance_after >= 0 AND quantity_after > 0),
    CONSTRAINT fk_takeover_execution_quote FOREIGN KEY (quote_id) REFERENCES takeover_quote(id),
    CONSTRAINT fk_takeover_execution_account FOREIGN KEY (buyer_account_id) REFERENCES personal_account(id),
    CONSTRAINT fk_takeover_execution_instrument FOREIGN KEY (instrument_id) REFERENCES market_instrument(id)
);

CREATE TABLE IF NOT EXISTS club_cash_transfer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transfer_key VARCHAR(36) NOT NULL,
    account_id BIGINT NOT NULL,
    profile_id BIGINT NOT NULL,
    team_id BIGINT NOT NULL,
    direction VARCHAR(16) NOT NULL,
    amount BIGINT NOT NULL,
    season_number INTEGER NOT NULL,
    game_day INTEGER NOT NULL,
    idempotency_key VARCHAR(140) NOT NULL,
    correlation_id VARCHAR(120) NOT NULL,
    personal_balance_after BIGINT NOT NULL,
    club_balance_after BIGINT NOT NULL,
    distributable_before BIGINT NOT NULL,
    CONSTRAINT uk_club_cash_transfer_public UNIQUE (transfer_key),
    CONSTRAINT uk_club_cash_transfer_retry UNIQUE (account_id, idempotency_key),
    CONSTRAINT ck_club_cash_transfer_values CHECK (
        direction IN ('INJECTION', 'WITHDRAWAL') AND amount > 0
        AND personal_balance_after >= 0 AND club_balance_after >= 0
        AND distributable_before >= 0),
    CONSTRAINT fk_club_cash_transfer_account FOREIGN KEY (account_id) REFERENCES personal_account(id)
);
CREATE INDEX IF NOT EXISTS idx_club_cash_transfer_team ON club_cash_transfer(team_id, id);
