-- FORGE Training extensions — units, coach assignment, mentoring groups.
-- H2-only, save/load via SAVE_VERSION_9 (ddl-auto covers other dialects).

CREATE TABLE IF NOT EXISTS player_unit_assignment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id BIGINT NOT NULL,
    player_id BIGINT NOT NULL,
    unit VARCHAR(20) NOT NULL,
    auto_assigned BOOLEAN DEFAULT TRUE NOT NULL,
    version BIGINT DEFAULT 0 NOT NULL,
    CONSTRAINT uk_player_unit UNIQUE (team_id, player_id),
    CONSTRAINT ck_player_unit CHECK (unit IN ('GOALKEEPING', 'DEFENCE', 'ATTACK'))
);
CREATE INDEX IF NOT EXISTS idx_player_unit_team ON player_unit_assignment (team_id);

CREATE TABLE IF NOT EXISTS unit_coach_assignment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id BIGINT NOT NULL,
    coach_id BIGINT NOT NULL,
    unit VARCHAR(20) NOT NULL,
    version BIGINT DEFAULT 0 NOT NULL,
    CONSTRAINT uk_unit_coach UNIQUE (team_id, coach_id, unit),
    CONSTRAINT ck_unit_coach CHECK (unit IN ('GOALKEEPING', 'DEFENCE', 'ATTACK'))
);
CREATE INDEX IF NOT EXISTS idx_unit_coach_team ON unit_coach_assignment (team_id);

CREATE TABLE IF NOT EXISTS mentoring_group (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id BIGINT NOT NULL,
    name VARCHAR(120) NOT NULL,
    version BIGINT DEFAULT 0 NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_mentoring_group_team ON mentoring_group (team_id);

CREATE TABLE IF NOT EXISTS mentoring_group_member (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    team_id BIGINT NOT NULL,
    player_id BIGINT NOT NULL,
    mentor BOOLEAN DEFAULT FALSE NOT NULL,
    version BIGINT DEFAULT 0 NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_mentoring_member_group ON mentoring_group_member (group_id);
CREATE INDEX IF NOT EXISTS idx_mentoring_member_team ON mentoring_group_member (team_id);
