ALTER TABLE human ADD COLUMN IF NOT EXISTS stay_forward BOOLEAN DEFAULT FALSE;
UPDATE human SET stay_forward = FALSE WHERE stay_forward IS NULL;
ALTER TABLE human ALTER COLUMN stay_forward SET DEFAULT FALSE;
ALTER TABLE human ALTER COLUMN stay_forward SET NOT NULL;
