ALTER TABLE market_instrument ADD COLUMN IF NOT EXISTS risk_class VARCHAR(24) DEFAULT 'SAFE_COMPANY' NOT NULL;
ALTER TABLE market_instrument ADD COLUMN IF NOT EXISTS risk_config_version VARCHAR(32) DEFAULT 'risk-v1' NOT NULL;

UPDATE market_instrument SET risk_class = 'CLUB_EQUITY' WHERE instrument_type = 'CLUB';
UPDATE market_instrument SET risk_class = 'SPECULATIVE' WHERE code = 'MEDIA11';

ALTER TABLE market_instrument ADD CONSTRAINT IF NOT EXISTS ck_market_instrument_risk_class
    CHECK (risk_class IN ('SAFE_COMPANY', 'SPECULATIVE', 'CLUB_EQUITY'));
ALTER TABLE market_instrument ADD CONSTRAINT IF NOT EXISTS ck_market_instrument_risk_type
    CHECK ((instrument_type = 'CLUB' AND risk_class = 'CLUB_EQUITY')
        OR (instrument_type = 'COMPANY' AND risk_class IN ('SAFE_COMPANY', 'SPECULATIVE')));

CREATE TABLE IF NOT EXISTS trader_adviser_contract (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    profile_id BIGINT NOT NULL,
    adviser_code VARCHAR(40) NOT NULL,
    skill INTEGER NOT NULL,
    reputation INTEGER NOT NULL,
    salary_per_day BIGINT NOT NULL,
    contract_start_absolute_day BIGINT NOT NULL,
    contract_end_absolute_day BIGINT NOT NULL,
    last_paid_absolute_day BIGINT NOT NULL,
    advice_seed BIGINT NOT NULL,
    model_version VARCHAR(32) NOT NULL,
    hire_idempotency_key VARCHAR(140) NOT NULL,
    active BOOLEAN DEFAULT TRUE NOT NULL,
    termination_reason VARCHAR(80),
    version BIGINT DEFAULT 0 NOT NULL,
    CONSTRAINT uk_trader_adviser_hire_retry UNIQUE (account_id, hire_idempotency_key),
    CONSTRAINT ck_trader_adviser_quality CHECK (skill BETWEEN 0 AND 100 AND reputation BETWEEN 0 AND 100),
    CONSTRAINT ck_trader_adviser_salary CHECK (salary_per_day >= 0),
    CONSTRAINT ck_trader_adviser_dates CHECK (
        contract_start_absolute_day > 0
        AND contract_end_absolute_day >= contract_start_absolute_day
        AND last_paid_absolute_day >= contract_start_absolute_day - 1
        AND last_paid_absolute_day <= contract_end_absolute_day),
    CONSTRAINT fk_trader_adviser_account FOREIGN KEY (account_id) REFERENCES personal_account(id)
);
CREATE INDEX IF NOT EXISTS idx_trader_adviser_profile_active
    ON trader_adviser_contract(profile_id, active, contract_end_absolute_day);

CREATE TABLE IF NOT EXISTS trader_advice_recommendation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id BIGINT NOT NULL,
    instrument_id BIGINT NOT NULL,
    season_number INTEGER NOT NULL,
    game_day INTEGER NOT NULL,
    action VARCHAR(8) NOT NULL,
    risk_class VARCHAR(24) NOT NULL,
    horizon_days INTEGER NOT NULL,
    confidence DECIMAL(8,4) NOT NULL,
    risk DECIMAL(8,4) NOT NULL,
    trailing_return DECIMAL(20,8) NOT NULL,
    observed_volatility DECIMAL(20,8) NOT NULL,
    explanation VARCHAR(300) NOT NULL,
    model_version VARCHAR(32) NOT NULL,
    CONSTRAINT uk_trader_advice_day UNIQUE (contract_id, instrument_id, season_number, game_day),
    CONSTRAINT ck_trader_advice_date CHECK (season_number >= 1 AND game_day BETWEEN 1 AND 366),
    CONSTRAINT ck_trader_advice_action CHECK (action IN ('BUY', 'SELL', 'HOLD')),
    CONSTRAINT ck_trader_advice_risk_class CHECK (risk_class IN ('SAFE_COMPANY', 'SPECULATIVE', 'CLUB_EQUITY')),
    CONSTRAINT ck_trader_advice_values CHECK (
        horizon_days > 0 AND confidence BETWEEN 0 AND 1 AND risk BETWEEN 0 AND 1
        AND observed_volatility >= 0),
    CONSTRAINT fk_trader_advice_contract FOREIGN KEY (contract_id) REFERENCES trader_adviser_contract(id),
    CONSTRAINT fk_trader_advice_instrument FOREIGN KEY (instrument_id) REFERENCES market_instrument(id)
);
