CREATE TABLE IF NOT EXISTS player_position_familiarity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id BIGINT NOT NULL,
    position_code VARCHAR(8) NOT NULL,
    familiarity INTEGER NOT NULL,
    primary_position BOOLEAN DEFAULT FALSE NOT NULL,
    version BIGINT DEFAULT 0 NOT NULL,
    CONSTRAINT uk_player_position_familiarity UNIQUE (player_id, position_code),
    CONSTRAINT ck_player_position_code CHECK (position_code IN (
        'GK', 'DC', 'DL', 'DR', 'WBL', 'WBR', 'DM', 'MC', 'ML', 'MR', 'AMC', 'AML', 'AMR', 'ST')),
    CONSTRAINT ck_player_position_familiarity CHECK (familiarity BETWEEN 1 AND 20),
    CONSTRAINT fk_player_position_human FOREIGN KEY (player_id) REFERENCES human(id)
);
CREATE INDEX IF NOT EXISTS idx_player_position_familiarity_player
    ON player_position_familiarity(player_id);

CREATE TABLE IF NOT EXISTS player_role_familiarity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id BIGINT NOT NULL,
    position_code VARCHAR(8) NOT NULL,
    role_code VARCHAR(48) NOT NULL,
    familiarity INTEGER NOT NULL,
    version BIGINT DEFAULT 0 NOT NULL,
    CONSTRAINT uk_player_role_familiarity UNIQUE (player_id, position_code, role_code),
    CONSTRAINT ck_player_role_position_code CHECK (position_code IN (
        'GK', 'DC', 'DL', 'DR', 'WBL', 'WBR', 'DM', 'MC', 'ML', 'MR', 'AMC', 'AML', 'AMR', 'ST')),
    CONSTRAINT ck_player_role_familiarity CHECK (familiarity BETWEEN 1 AND 20),
    CONSTRAINT fk_player_role_human FOREIGN KEY (player_id) REFERENCES human(id)
);
CREATE INDEX IF NOT EXISTS idx_player_role_familiarity_player
    ON player_role_familiarity(player_id);

CREATE TABLE IF NOT EXISTS player_foot_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id BIGINT NOT NULL,
    left_foot_rating INTEGER NOT NULL,
    right_foot_rating INTEGER NOT NULL,
    version BIGINT DEFAULT 0 NOT NULL,
    CONSTRAINT uk_player_foot_profile_player UNIQUE (player_id),
    CONSTRAINT ck_player_foot_profile_ratings CHECK (
        left_foot_rating BETWEEN 1 AND 20 AND right_foot_rating BETWEEN 1 AND 20),
    CONSTRAINT fk_player_foot_profile_human FOREIGN KEY (player_id) REFERENCES human(id)
);

INSERT INTO player_position_familiarity (
    player_id, position_code, familiarity, primary_position, version)
SELECT h.id, UPPER(TRIM(h.position)), 20, TRUE, 0
FROM human h
WHERE h.type_id = 1
  AND h.position IS NOT NULL
  AND UPPER(TRIM(h.position)) IN (
      'GK', 'DC', 'DL', 'DR', 'WBL', 'WBR', 'DM', 'MC', 'ML', 'MR', 'AMC', 'AML', 'AMR', 'ST')
  AND NOT EXISTS (
      SELECT 1 FROM player_position_familiarity existing
      WHERE existing.player_id = h.id AND existing.position_code = UPPER(TRIM(h.position)))
ORDER BY h.id;

INSERT INTO player_foot_profile (
    player_id, left_foot_rating, right_foot_rating, version)
SELECT h.id,
       CASE h.preferred_foot
           WHEN 'Left' THEN 20
           WHEN 'Both' THEN 16
           ELSE 8
       END,
       CASE h.preferred_foot
           WHEN 'Left' THEN 8
           WHEN 'Both' THEN 16
           ELSE 20
       END,
       0
FROM human h
WHERE h.type_id = 1
  AND NOT EXISTS (
      SELECT 1 FROM player_foot_profile existing
      WHERE existing.player_id = h.id)
ORDER BY h.id;
