CREATE TABLE chairman_tactical_mandate (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id BIGINT NOT NULL,
    required_formation VARCHAR(32),
    updated_by_profile_id BIGINT NOT NULL,
    updated_season INT NOT NULL,
    updated_game_day INT NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_chairman_tactical_mandate_team UNIQUE (team_id)
);

CREATE TABLE chairman_tactical_mandate_slot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mandate_id BIGINT NOT NULL,
    position_index INT NOT NULL,
    required_player_id BIGINT NOT NULL,
    CONSTRAINT uk_mandate_slot_position UNIQUE (mandate_id, position_index),
    CONSTRAINT uk_mandate_slot_player UNIQUE (mandate_id, required_player_id),
    CONSTRAINT fk_mandate_slot_mandate FOREIGN KEY (mandate_id)
        REFERENCES chairman_tactical_mandate(id) ON DELETE CASCADE
);
