CREATE TABLE IF NOT EXISTS manager_inbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id BIGINT NOT NULL,
    season_number INT NOT NULL,
    round_number INT NOT NULL,
    title VARCHAR(255),
    content CLOB,
    category VARCHAR(255),
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at BIGINT NOT NULL,
    recipient_profile_id BIGINT,
    audience VARCHAR(16) NOT NULL DEFAULT 'MANAGER',
    deduplication_key VARCHAR(255)
);

ALTER TABLE manager_inbox ADD COLUMN IF NOT EXISTS recipient_profile_id BIGINT;
ALTER TABLE manager_inbox ADD COLUMN IF NOT EXISTS audience VARCHAR(16) NOT NULL DEFAULT 'MANAGER';
ALTER TABLE manager_inbox ADD COLUMN IF NOT EXISTS deduplication_key VARCHAR(255);
CREATE UNIQUE INDEX IF NOT EXISTS uk_manager_inbox_recipient_dedup
    ON manager_inbox(recipient_profile_id, deduplication_key);
CREATE INDEX IF NOT EXISTS ix_manager_inbox_recipient
    ON manager_inbox(recipient_profile_id, id);
