package com.footballmanagergamesimulator.service;

import com.footballmanagergamesimulator.model.PlayerSkills;
import com.footballmanagergamesimulator.model.Scorer;
import org.springframework.stereotype.Service;

import java.util.*;
import java.util.function.BiConsumer;

@Service
public class CompetitionService {

    /**
     * Injected rather than read from the static holder, so Spring is forced to build the
     * importance table before this service exists.
     *
     * <p>Bootstrap runs from {@code CompetitionController}'s {@code @PostConstruct} and
     * reaches generation through this bean. With only the static lookup there was no
     * dependency edge, initialisation order was undefined, and the entire opening squad
     * of the game was generated by the legacy profile while every later player used the
     * engine weights — two populations on two different scales, with nothing to show for it.
     */
    @org.springframework.beans.factory.annotation.Autowired
    private PositionAttributeImportance attributeImportance;

    /**
     * Generate realistic player attributes based on position and overall rating.
     * Each position has a profile defining which attributes should be high/medium/low.
     * The rating (1-300 scale) determines the base quality level, which maps to 1-20 attributes.
     *
     * Profile tiers for each attribute:
     *   HIGH   = core attribute for position (e.g., finishing for ST)
     *   MEDIUM = relevant but secondary (e.g., passing for ST)
     *   LOW    = not very relevant (e.g., marking for ST)
     */
    public void generateSkills(PlayerSkills playerSkills, double rating) {
        generateSkills(playerSkills, rating, new Random());
    }

    /**
     * Seeded variant — callers (e.g. {@code SquadGenerationService},
     * tests) can pass a deterministic {@link Random} so the generated
     * attributes are reproducible.
     */
    public void generateSkills(PlayerSkills playerSkills, double rating, Random random) {
        String position = playerSkills.getPosition();
        if (position == null) position = "MC";
        position = position.trim().toUpperCase(Locale.ROOT);

        // Legacy fallback also stops at 19. Attribute 20 is reserved for hand-authored
        // exceptional abilities and must never appear from ordinary generation.
        double baseLevel = Math.max(1, Math.min(19, rating / 15.0));

        // Importance comes from the weights the match engine scores with, so what a
        // position is given is what that position is actually worth on the pitch. The
        // hand-written profile below is the fallback for anything the engine config does
        // not describe, and for unit tests that build this service outside Spring.
        PositionAttributeImportance engineImportance =
                attributeImportance != null ? attributeImportance : PositionAttributeImportance.current();
        // Compartment V1 defines fine positions explicitly. Collapsing AML->ML or AMC->MC here
        // produced a rating from one vector and evaluated the player with another vector in matches.
        if (engineImportance != null && engineImportance.knows(position)) {
            generateFromEngineWeights(playerSkills, position, rating, engineImportance, random);
            return;
        }

        // Historical non-Spring fallback retained only for isolated legacy tests.
        position = TacticService.getBasePosition(position);

        Map<String, Double> profile = getPositionProfile(position);

        for (Map.Entry<String, BiConsumer<PlayerSkills, Integer>> entry : PlayerSkillsService.SETTER_MAP.entrySet()) {
            String attrName = entry.getKey();
            double importance = profile.getOrDefault(attrName, 0.5); // default medium-low

            // importance: 1.0 = core attribute, 0.7 = secondary, 0.3 = minor
            // Spread: core attributes cluster near baseLevel, minor ones spread wider below
            double targetLevel = baseLevel * importance;

            // Add randomness: ±2 for variety
            double variance = random.nextGaussian() * 1.5;
            int value = (int) Math.round(targetLevel + variance);
            value = Math.max(1, Math.min(19, value));

            entry.getValue().accept(playerSkills, value);
        }

        // GK attributes: only high for goalkeepers, very low for outfield
        if (!"GK".equals(position)) {
            playerSkills.setHandling(random.nextInt(1, 4));
            playerSkills.setReflexes(random.nextInt(1, 4));
            playerSkills.setOneOnOnes(random.nextInt(1, 4));
            playerSkills.setCommandOfArea(random.nextInt(1, 4));
            playerSkills.setKicking(random.nextInt(1, 6));
            playerSkills.setThrowing(random.nextInt(1, 4));
        }
    }

    /**
     * Build a position-specific attribute importance profile.
     * Values: 1.0 = primary, 0.85 = strong, 0.7 = secondary, 0.5 = average, 0.3 = minor
     */
    /**
     * Distributes a rating across the attributes that position is scored on.
     *
     * <p>Every attribute the engine weights for this position is set to
     * {@code level x importance}; anything the engine does not read for the position
     * still gets a floor so a player is not left with 1s in attributes that never
     * feature in his valuation but do show on his profile.
     *
     * <p>Noise is deliberately small and symmetric. It exists so two players on the same
     * rating are not identical, not to decide how good they are — that is the rating's
     * job, and the two used to disagree by up to 26%.
     */
    private void generateFromEngineWeights(PlayerSkills playerSkills, String position, double rating,
                                           PositionAttributeImportance table, Random random) {
        Map<com.footballmanagergamesimulator.compartment.PlayerAttribute, Double> generationShape =
                table.generationImportance(position);
        int attributeMin = table.attributeMin();
        int attributeMax = table.attributeMax();
        double span = attributeMax - attributeMin;
        double fraction = Math.max(0.0, Math.min(1.0, rating / 300.0));

        for (com.footballmanagergamesimulator.compartment.PlayerAttribute attribute
                : com.footballmanagergamesimulator.compartment.PlayerAttribute.values()) {
            double shape = generationShape.getOrDefault(attribute, MIN_DISPLAY_IMPORTANCE);
            // Work in the same normalized [attributeMin, attributeMax] space as the
            // canonical calculator. Randomness changes the profile, never its final
            // canonical magnitude: calibrateOverallRating projects it back afterwards.
            double target = attributeMin + span * fraction * shape;
            double noiseScale = span * fraction * shape * 0.04 * (1.0 - fraction);
            int value = (int) Math.round(target + random.nextGaussian() * noiseScale);
            com.footballmanagergamesimulator.compartment.adapter.PlayerAttributeMapping
                    .setValue(playerSkills, attribute,
                            Math.max(attributeMin, Math.min(attributeMax, value)));
        }

        // The engine scores 29 attributes; a player has 42. Corners, free kicks, flair and
        // the rest are shown on his profile and used elsewhere in the game, so they still
        // need a sane value — left unset they stayed at 0, outside the 1-20 scale entirely.
        // They track his level without steering it, since nothing in the match reads them.
        double baseLevel = attributeMin + span * fraction;
        int filler = Math.max(attributeMin, Math.min(attributeMax,
                (int) Math.round(attributeMin + (baseLevel - attributeMin) * 0.45)));
        for (Map.Entry<String, BiConsumer<PlayerSkills, Integer>> entry
                : PlayerSkillsService.SETTER_MAP.entrySet()) {
            if (PlayerSkillsService.GETTER_MAP.get(entry.getKey()).apply(playerSkills) >= 1) continue;
            entry.getValue().accept(playerSkills, filler);
        }

        // Keeper handling is positional, not an attribute the outfield profile can express:
        // an outfielder with real reflexes would be scored as a competent emergency keeper.
        if (!"GK".equals(position)) {
            playerSkills.setHandling(random.nextInt(1, 4));
            playerSkills.setReflexes(random.nextInt(1, 4));
            playerSkills.setOneOnOnes(random.nextInt(1, 4));
            playerSkills.setCommandOfArea(random.nextInt(1, 4));
            playerSkills.setKicking(random.nextInt(1, 6));
            playerSkills.setThrowing(random.nextInt(1, 4));
        }

        // The requested rating is authoritative at creation time. Integer attributes
        // make the inverse discrete, so choose the closest representable canonical value.
        PlayerSkillsService.calibrateOverallRating(playerSkills, rating);
    }

    private static final double MIN_DISPLAY_IMPORTANCE = 0.25;

    private Map<String, Double> getPositionProfile(String position) {
        Map<String, Double> profile = new HashMap<>();

        // Default all to medium
        for (String attr : PlayerSkillsService.GETTER_MAP.keySet()) {
            profile.put(attr, 0.55);
        }

        switch (position) {
            case "GK" -> {
                // GK: goalkeeper attrs high, outfield low
                profile.put("Handling", 1.0);
                profile.put("Reflexes", 1.0);
                profile.put("One On Ones", 0.9);
                profile.put("Command Of Area", 0.9);
                profile.put("Kicking", 0.8);
                profile.put("Throwing", 0.75);
                profile.put("Positioning", 0.85);
                profile.put("Concentration", 0.8);
                profile.put("Anticipation", 0.8);
                profile.put("Composure", 0.75);
                profile.put("Agility", 0.8);
                profile.put("Decisions", 0.7);
                profile.put("Bravery", 0.7);
                // Low for outfield attrs
                profile.put("Dribbling", 0.2);
                profile.put("Finishing", 0.1);
                profile.put("Crossing", 0.1);
                profile.put("Tackling", 0.15);
                profile.put("Marking", 0.1);
                profile.put("Off The Ball", 0.1);
                profile.put("Long Shots", 0.1);
                profile.put("Heading", 0.2);
                profile.put("Flair", 0.2);
                profile.put("Vision", 0.25);
            }
            case "DC" -> {
                profile.put("Tackling", 1.0);
                profile.put("Marking", 0.95);
                profile.put("Positioning", 0.95);
                profile.put("Heading", 0.85);
                profile.put("Strength", 0.85);
                profile.put("Anticipation", 0.85);
                profile.put("Concentration", 0.85);
                profile.put("Bravery", 0.8);
                profile.put("Composure", 0.75);
                profile.put("Jumping Reach", 0.8);
                profile.put("Pace", 0.7);
                profile.put("Passing", 0.6);
                profile.put("Decisions", 0.7);
                profile.put("Teamwork", 0.7);
                profile.put("Aggression", 0.7);
                // Low
                profile.put("Finishing", 0.2);
                profile.put("Crossing", 0.25);
                profile.put("Dribbling", 0.3);
                profile.put("Flair", 0.2);
                profile.put("Off The Ball", 0.3);
                profile.put("Long Shots", 0.2);
            }
            case "DL", "DR" -> {
                profile.put("Tackling", 0.85);
                profile.put("Crossing", 0.85);
                profile.put("Pace", 0.9);
                profile.put("Stamina", 0.85);
                profile.put("Positioning", 0.8);
                profile.put("Marking", 0.75);
                profile.put("Anticipation", 0.75);
                profile.put("Work Rate", 0.85);
                profile.put("Dribbling", 0.7);
                profile.put("Passing", 0.7);
                profile.put("Acceleration", 0.85);
                profile.put("Concentration", 0.7);
                profile.put("Teamwork", 0.75);
                profile.put("First Touch", 0.65);
                profile.put("Decisions", 0.65);
                // Low
                profile.put("Finishing", 0.25);
                profile.put("Heading", 0.4);
                profile.put("Long Shots", 0.3);
                profile.put("Composure", 0.5);
            }
            case "MC" -> {
                profile.put("Passing", 0.95);
                profile.put("Vision", 0.85);
                profile.put("Decisions", 0.85);
                profile.put("Teamwork", 0.8);
                profile.put("First Touch", 0.8);
                profile.put("Technique", 0.8);
                profile.put("Stamina", 0.8);
                profile.put("Work Rate", 0.8);
                profile.put("Positioning", 0.75);
                profile.put("Tackling", 0.7);
                profile.put("Concentration", 0.7);
                profile.put("Composure", 0.75);
                profile.put("Anticipation", 0.7);
                profile.put("Dribbling", 0.65);
                profile.put("Long Shots", 0.65);
                // Lower
                profile.put("Heading", 0.4);
                profile.put("Crossing", 0.45);
                profile.put("Off The Ball", 0.5);
                profile.put("Marking", 0.5);
            }
            case "ML", "MR" -> {
                profile.put("Crossing", 0.9);
                profile.put("Dribbling", 0.9);
                profile.put("Pace", 0.9);
                profile.put("Acceleration", 0.85);
                profile.put("Technique", 0.8);
                profile.put("First Touch", 0.75);
                profile.put("Off The Ball", 0.75);
                profile.put("Flair", 0.7);
                profile.put("Passing", 0.7);
                profile.put("Stamina", 0.75);
                profile.put("Work Rate", 0.7);
                profile.put("Agility", 0.75);
                profile.put("Finishing", 0.65);
                profile.put("Decisions", 0.65);
                profile.put("Anticipation", 0.65);
                // Low
                profile.put("Tackling", 0.35);
                profile.put("Marking", 0.3);
                profile.put("Heading", 0.35);
                profile.put("Positioning", 0.5);
            }
            case "ST" -> {
                profile.put("Finishing", 1.0);
                profile.put("Off The Ball", 0.9);
                profile.put("Composure", 0.85);
                profile.put("First Touch", 0.8);
                profile.put("Dribbling", 0.75);
                profile.put("Heading", 0.7);
                profile.put("Pace", 0.75);
                profile.put("Acceleration", 0.7);
                profile.put("Anticipation", 0.75);
                profile.put("Technique", 0.7);
                profile.put("Strength", 0.7);
                profile.put("Decisions", 0.65);
                profile.put("Flair", 0.6);
                profile.put("Balance", 0.6);
                profile.put("Agility", 0.65);
                profile.put("Long Shots", 0.55);
                // Low
                profile.put("Tackling", 0.2);
                profile.put("Marking", 0.15);
                profile.put("Positioning", 0.4);
                profile.put("Crossing", 0.35);
                profile.put("Concentration", 0.45);
            }
        }

        return profile;
    }

    // ideea e ca un ST sa aiba sanse mai mari sa dea gol decat un mijlocas
    public double getDifferentValueForScoringBasedOnPosition(Scorer scorer) {

        // More skewed weights — strikers now dominate goal share like in real football,
        // defenders are very unlikely to score (matches reality of set-pieces/headers).
        // Quadratic on rating so a 90-rated striker towers over a 70-rated one
        // (allowing realistic hat-tricks from star players).
        Map<String, Double> positionToValue = Map.of("GK", 0D,
                "DL", 0.4,
                "DR", 0.4,
                "DC", 0.5,
                "ML", 1.6,
                "MR", 1.6,
                "MC", 1.8,
                "ST", 4.0);

        double posMul = positionToValue.getOrDefault(scorer.getPosition(), 0.8D);
        // Quadratic rating boost: rating² / 70 keeps a baseline-70 player ≈ unchanged
        // while a 90-rated player gets ~1.65x weight relative to baseline.
        double ratingFactor = (scorer.getRating() * scorer.getRating()) / 70D;
        double totalRating = posMul * ratingFactor;

        if (scorer.isSubstitute()) {
            totalRating /= 2;
        }

        return Math.max(totalRating, 0D);
    }
}
