-- CONCORD Team Dynamics (feature flag dynamics.enabled, default OFF) — PostgreSQL.
-- Monthly team meeting, contextual player conversations and their promises.

CREATE TABLE IF NOT EXISTS team_meeting (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id BIGINT NOT NULL,
    season INTEGER NOT NULL,
    month_index INTEGER NOT NULL,
    held_day INTEGER DEFAULT 0 NOT NULL,
    context VARCHAR(40) NOT NULL,
    tone VARCHAR(40) NOT NULL,
    manager_reputation DOUBLE PRECISION DEFAULT 0 NOT NULL,
    participant_count INTEGER DEFAULT 0 NOT NULL,
    average_morale_delta DOUBLE PRECISION DEFAULT 0 NOT NULL,
    summary VARCHAR(1000),
    created_at_epoch_millis BIGINT DEFAULT 0 NOT NULL,
    version BIGINT DEFAULT 0 NOT NULL,
    CONSTRAINT uk_team_meeting_team_season_month UNIQUE (team_id, season, month_index),
    CONSTRAINT ck_team_meeting_month CHECK (month_index BETWEEN 1 AND 12)
);

CREATE TABLE IF NOT EXISTS team_meeting_reaction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_id BIGINT NOT NULL,
    team_id BIGINT NOT NULL,
    player_id BIGINT NOT NULL,
    player_name VARCHAR(120),
    tier VARCHAR(30),
    reaction VARCHAR(20) NOT NULL,
    morale_before DOUBLE PRECISION DEFAULT 0 NOT NULL,
    morale_delta DOUBLE PRECISION DEFAULT 0 NOT NULL,
    reason VARCHAR(500)
);
CREATE INDEX IF NOT EXISTS idx_tm_reaction_meeting ON team_meeting_reaction (meeting_id);

CREATE TABLE IF NOT EXISTS player_conversation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id BIGINT NOT NULL,
    player_id BIGINT NOT NULL,
    player_name VARCHAR(120),
    season INTEGER NOT NULL,
    month_index INTEGER NOT NULL,
    held_day INTEGER DEFAULT 0 NOT NULL,
    topic VARCHAR(40) NOT NULL,
    tone VARCHAR(40) NOT NULL,
    manager_reputation DOUBLE PRECISION DEFAULT 0 NOT NULL,
    reaction VARCHAR(20) NOT NULL,
    morale_before DOUBLE PRECISION DEFAULT 0 NOT NULL,
    morale_delta DOUBLE PRECISION DEFAULT 0 NOT NULL,
    player_response VARCHAR(1000),
    summary VARCHAR(1000),
    created_at_epoch_millis BIGINT DEFAULT 0 NOT NULL,
    version BIGINT DEFAULT 0 NOT NULL,
    CONSTRAINT uk_player_conversation_player_season_month UNIQUE (player_id, season, month_index),
    CONSTRAINT ck_player_conversation_month CHECK (month_index BETWEEN 1 AND 12)
);
CREATE INDEX IF NOT EXISTS idx_player_conversation_team ON player_conversation (team_id);

CREATE TABLE IF NOT EXISTS dynamics_promise (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id BIGINT NOT NULL,
    player_id BIGINT NOT NULL,
    player_name VARCHAR(120),
    season INTEGER NOT NULL,
    month_index INTEGER NOT NULL,
    created_day INTEGER DEFAULT 0 NOT NULL,
    source VARCHAR(30) NOT NULL,
    source_id BIGINT DEFAULT 0 NOT NULL,
    type VARCHAR(40) NOT NULL,
    status VARCHAR(20) NOT NULL,
    description VARCHAR(500),
    due_season INTEGER DEFAULT 0 NOT NULL,
    due_day INTEGER DEFAULT 0 NOT NULL,
    created_at_epoch_millis BIGINT DEFAULT 0 NOT NULL,
    resolved_at_epoch_millis BIGINT,
    version BIGINT DEFAULT 0 NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_dyn_promise_team ON dynamics_promise (team_id);
CREATE INDEX IF NOT EXISTS idx_dyn_promise_player ON dynamics_promise (player_id);
